name: school_police
description: 'A new Flutter project.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  flutter_svg: ^2.0.9
  path: 1.9.0
  url_launcher: ^6.1.8
  flutter_bloc: ^8.1.6
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  location: ^5.0.0
  geolocator: ^9.0.0
  firebase_messaging: ^15.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/google-maps.png
